[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python api_server.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[healthcheck]
path = "/health"
timeout = 30

[environment]
ENVIRONMENT = "production"
