services:
  - type: web
    name: agentic-ai-agent
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python api_server.py
    
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: ENVIRONMENT
        value: production
      - key: PORT
        value: 10000
    
    healthCheckPath: /health
    
    autoDeploy: true
